# Generated by Django 2.0.2 on 2023-06-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20230620_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='email',
        ),
    ]
